#!/usr/bin/env python3
"""Report exact core and adapter relationships as JSON; never tests model behavior."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import package_plugins
from release_contract import ROOT, load_contract, require_selected


def describe(raw: bytes) -> dict:
    return {"sha256": hashlib.sha256(raw).hexdigest(), "bytes": len(raw),
            "characters": len(raw.decode("utf-8"))}


def inspect(root: Path = ROOT, *, site: Path | None = None,
            downloads: Path | None = None, generated: bool = False) -> dict:
    contract = load_contract(root)
    report = {"version": contract["version"], "selection_status": contract["status"],
              "scope": "Source bytes and wrapper relationships only",
              "behavior_tested": False, "core": {}, "adapters": {}, "files_checked": [], "errors": []}
    core = {lang: (root / f"assets/core.{lang}.txt").read_bytes() for lang in ("ru", "en")}
    for lang, raw in core.items():
        report["core"][lang] = {"kind": "exact-core", **describe(raw)}
    try:
        require_selected(root)
    except ValueError as error:
        report["errors"].append(str(error))
        report["status"] = "blocked"
        return report

    def equal(path: Path, expected: bytes, kind: str) -> None:
        if not path.is_file() or path.is_symlink():
            report["errors"].append(f"Missing or non-regular generated file: {path}")
            return
        actual = path.read_bytes()
        report["files_checked"].append({"path": str(path), "kind": kind,
                                        "expected_bytes_match": actual == expected, **describe(actual)})
        if actual != expected:
            report["errors"].append(f"Generated bytes differ: {path}")

    for lang, raw in core.items():
        full = raw
        medium = (root / f"assets/medium.{lang}.txt").read_bytes()
        compact = (root / f"assets/compact.{lang}.txt").read_bytes()
        skill = package_plugins.skill_text(lang, "read").encode("utf-8")
        if not skill.endswith(raw):
            report["errors"].append(f"Skill wrapper changed the {lang} core bytes")
        report["adapters"][lang] = {
            "full_download": {"kind": "exact-core", "core_offset": 0,
                              "core_bytes_match": full == raw, **describe(full)},
            "skill": {"kind": "frontmatter-and-scope-plus-exact-core",
                      "core_offset": len(skill) - len(raw), "core_bytes_match": skill.endswith(raw), **describe(skill)},
            "medium": {"kind": "separate-edition", "equals_core": medium == raw, **describe(medium)},
            "compact": {"kind": "separate-edition", "equals_core": compact == raw, **describe(compact)},
            "gpt_draft": {"kind": "medium-edition-without-second-scope", **describe(medium)},
        }
        if downloads:
            for edition, expected in (("core", full), ("5000", medium), ("compact", compact)):
                equal(downloads / f"beforeword_{edition}_{lang.upper()}.txt", expected,
                      "exact-core" if edition == "core" else "separate-edition")
        if site:
            for alias, expected in (("", full), ("full-", full), ("5000-", medium), ("compact-", compact), ("micro-", compact)):
                equal(site / "model" / f"beforeword-{alias}{lang}.txt", expected,
                      "exact-core" if alias in ("", "full-") else "separate-edition")
        if generated:
            equal(root / f"catalog/gpt-store/instructions.{lang}.txt", medium, "medium-edition")
            if lang == "en":
                for provider in ("openai", "claude"):
                    equal(root / f"plugins/{provider}/beforeword/skills/read/SKILL.md", skill, "skill-wrapper")
                root_skill = (root / "SKILL.md").read_bytes()
                if root_skill.count(raw) != 1:
                    report["errors"].append("Root SKILL.md must contain the complete selected EN core exactly once")
    report["status"] = "consistent" if not report["errors"] else "different"
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, help="Generated public_html directory")
    parser.add_argument("--downloads", type=Path, help="Generated versioned downloads directory")
    parser.add_argument("--generated", action="store_true", help="Also check catalog payloads and root SKILL.md")
    args = parser.parse_args()
    report = inspect(site=args.site, downloads=args.downloads, generated=args.generated)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["status"] == "consistent" else 2


if __name__ == "__main__":
    raise SystemExit(main())
